version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.15.1-browsers

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --frozen-lockfile
      - run:
          name: build
          command: npm run vscode:prepublish
      - run:
          name: upload test coverage
          command: npm run codecov
      - run:
          name: release
          command: npm run semantic-release
workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - github-release
            - vsce-release
